name: playground

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Playground in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: Build
        run: |
          cd playground
          yarn
          npm run build

      - uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          name: playground
          path: ./playground/dist

  release:
    name: Release to Github
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/master') && github.repository == 'whatchanged-community/whatchanged'
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: playground
          path: ./dist

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./dist # The folder the action should deploy.
